export type AttributeKey = 'STR'|'CON'|'SIZ'|'DEX'|'APP'|'INT'|'POW'|'EDU';
export const ATTRIBUTE_KEYS: AttributeKey[] = ['STR','CON','SIZ','DEX','APP','INT','POW','EDU'];
export type Attributes = Record<AttributeKey,number>;
export interface SkillDefinition {id:string;name:string;english:string;base:number|'DEX/2'|'EDU'|'APP/5';category:string;eras?:string[];description?:string;scenarios?:string[];sourceId?:string;parentId?:string;specialization?:boolean;note?:string}
export interface Occupation {id:string;name:string;english:string;description:string;formula:{edu:number;other?:string[];factor?:number};credit:[number,number];skills:string[];choiceCount?:number;choiceGroups?:{name:string;count:number;options:string[]}[];skillNotes?:string;eras?:string[];sourceId:string;version?:string;eraNote?:string;verificationSourceIds?:string[]}
export interface EquipmentDefinition {id:string;name:string;category:string;description:string;price:string;damage?:string;range?:string;attacks?:string;sourceId:string;verificationSourceIds?:string[];kind?:'weapon'|'item';skillId?:string;eras?:string[];ammo?:string;malfunction?:string;armor?:string}
export interface SpellDefinition {id:string;name:string;description:string;cost:string;sourceId:string}
export interface Ruleset {id:string;name:string;english:string;era:string;description:string;sourceId:string;status:string;skillBaseOverrides?:Record<string,number>;skillAliases?:Record<string,string>;skillDescriptions?:Record<string,SkillHelp>;notes?:string[]}
export interface SkillHelp {description:string;scenarios:string[]}
export interface RuleGuidance {attributes:Record<AttributeKey,{description:string;bands:{min:number;max:number;description:string}[]}>;build:{value:number;description:string}[];wealth:{min:number;max:number;label:string;description:string}[]}
export type SourceCoverage = 'complete'|'partial'|'not-included'|'not-applicable';
export interface RuleSource {id:string;title:string;url:string;note:string;publisher?:string;year?:number;edition?:string;kind?:'core'|'setting'|'rules'|'reference'|'character-sheet'|'original'|'user-reference';coverage?:{occupations:SourceCoverage;skills:SourceCoverage;equipment:SourceCoverage}}
export interface RuleData {version:string;sources:RuleSource[];rulesets:Ruleset[];skills:SkillDefinition[];occupations:Occupation[];equipment:EquipmentDefinition[];spells:SpellDefinition[];guidance?:RuleGuidance}
export interface SkillAllocation {occupation:number;personal:number;growth:number}
export interface InventoryItem {id:string;definitionId:string;name:string;quantity:number;notes:string;damage?:string;range?:string;attacks?:string;kind?:'weapon'|'item';skillId?:string;ammo?:string;malfunction?:string;armor?:string}
export interface Character {id:string;name:string;player:string;occupationId:string;rulesetId:string;enabledExtensionIds?:string[];age:number;gender:string;birthplace:string;residence:string;portrait:string;attributes:Attributes;luck:number;current:{hp:number|null;mp:number|null;san:number|null};skills:Record<string,SkillAllocation>;occupationChoices:string[];inventory:InventoryItem[];armor?:{value:number;notes:string};spellIds:string[];backstory:{appearance:string;ideology:string;people:string;places:string;possessions:string;traits:string;injuries:string;phobias:string;notes:string};money:{cash:string;assets:string;spending:string};createdAt:string;updatedAt:string}
export interface CustomContent {rulesets:Ruleset[];skills:SkillDefinition[];occupations:Occupation[];equipment:EquipmentDefinition[];spells:SpellDefinition[];sources?:RuleSource[];legacySourceIds?:string[]}
export interface Archive {schemaVersion:1;activeId:string;characters:Character[];custom:CustomContent}
